### ISSUE TITLE
Use different app name?

### ISSUE THREAD

**Issue by PowerBootWS** [adyanth/cloudflare-operator#103]
Is it possible, referring to the sample below, to bind the service to a different subdomain?  For example, instead of the subdomain being whoami.example.com for a service called 'whoami', can it be mysub.example.com to point to the whoami service?

apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: whoami-cluster-tun
subjects:
  - name: whoami **<--- this is the part I want to change, regardless of the service name.  Is there another way besides subjects.name?**
tunnelRef:
  kind: ClusterTunnel
  name: k3s-cluster-tunnel

**Comment by adyanth** [comment]
Please set the `subjects.spec.fqdn` to what it should be.

Ex:
```yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: whoami-cluster-tun
subjects:
  - name: whoami
    spec:
      fqdn: testing.domain.com # Make sure your operator config has access to domain.com
tunnelRef:
  kind: ClusterTunnel
  name: k3s-cluster-tunnel
```

More documentation in `kubectl explain`

```bash
❯ kubectl explain tunnelbinding.subjects.spec
GROUP:      networking.cfargotunnel.com
KIND:       TunnelBinding
VERSION:    v1alpha1

FIELD: spec <Object>


DESCRIPTION:
    <empty>
FIELDS:
  caPool        <string>
    CaPool trusts the CA certificate referenced by the key in the secret
    specified in tunnel.spec.originCaPool. tls.crt is trusted globally and does
    not need to be specified. Only useful if the protocol is HTTPS.

  fqdn  <string>
    Fqdn specifies the DNS name to access this service from. Defaults to the
    service.metadata.name + tunnel.spec.domain. If specifying this, make sure to
    use the same domain that the tunnel belongs to. This is not validated and
    used as provided

  noTlsVerify   <boolean>
    NoTlsVerify sisables TLS verification for this service. Only useful if the
    protocol is HTTPS.

  protocol      <string>
    Protocol specifies the protocol for the service. Should be one of http,
    https, tcp, udp, ssh or rdp. Defaults to http, with the exceptions of https
    for 443, smb for 139 and 445, rdp for 3389 and ssh for 22 if the service has
    a TCP port. The only available option for a UDP port is udp, which is
    default.

  target        <string>
    Target specified where the tunnel should proxy to. Defaults to the form of
    <protocol>://<service.metadata.name>.<service.metadata.namespace>.svc:<port>
```
