### ISSUE TITLE
spec.target is specified with https and 443 but status.services.target is showing http and 80

### ISSUE THREAD

**Issue by milagrofrost** [adyanth/cloudflare-operator#107]
Not sure if I'm using this incorrectly or not.  I'm using Cilium Gateway with my Cloudflare Operator.  

The gateway listens on ports 80 and 443.  My spec.target is set as "https://cilium-gateway-gateway-home.default.svc:443" but the status of the tunnel says the target is "http://cilium-gateway-gateway-home.default.svc:80".

If I set spec.protocol to 'https', my status shows as https://cilium-gateway-gateway-home.default.svc:80.

TunnelBinding's -o yaml (with spec.protocol 'https')

```
❯ kubectl get tunnelbindings.networking.cfargotunnel.com tunnel-home -o yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  finalizers:
  - cfargotunnel.com/finalizer
  generation: 3
  labels:
    app: home
    cfargotunnel.com/kind: TunnelBinding
    cfargotunnel.com/name: k3s-cluster-tunnel
  name: tunnel-home
  namespace: default
status:
  hostnames: home.*****.in
  services:
  - hostname: home.*****.in
  
    target: https://cilium-gateway-gateway-home.default.svc:80

subjects:
- kind: Service
  name: cilium-gateway-gateway-home
  spec:
    fqdn: home.*****.in
    noTlsVerify: false
    protocol: https
    proxyAddress: 127.0.0.1
    proxyPort: 0
    proxyType: ""

    target: https://cilium-gateway-gateway-home.default.svc:443

tunnelRef:
  disableDNSUpdates: false
  kind: ClusterTunnel
  name: k3s-cluster-tunnel
```

  
I feel like if I specify spec.target, the operator shouldn't have to generate a new target string and ignore the target that i set in spec.target (as I'm seeing in the getConfigForSubject function where it selects the first port of the service with service.Spec.Ports[0]) .

 My tunnel will work when spec.target is set to http://cilium-gateway-gateway-home.default.svc:80, but would like to use my https/443 endpoint of my service.
