### ISSUE TITLE
Working with Kubernetes Dashboard

### ISSUE THREAD

**Issue by Rahulsharma0810** [adyanth/cloudflare-operator#114]
Has anyone tried this with New Kubernetes Dashboard 7.0, Kong Service ? 

i am getting below error, with or without http/https

<img width="894" alt="Untitled" src="https://github.com/user-attachments/assets/70dcf941-b42e-4b08-a8c7-6fec49bb9277">

```
# HomeLab-Kubernetes/manifests/infrastructure/dashboard/tunnel-binding-ingress.yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: kubedash-tunnel-binding
  namespace: kubernetes-dashboard
subjects:
- name: kubernetes-dashboard-kubernetes-dashboard-kong-proxy
  spec:
    fqdn: dashboard.domain.com
    protocol: http
    noTlsVerify: true
tunnelRef:
  kind: ClusterTunnel
  name: i1-1806-talos-proxmox-cluster-tunnel

```

I have also tried opening svc to port 80 (default was 443)

```
#values.yaml
    kong:
      enabled: true
      proxy:
        http:
          type: ClusterIP
          enabled: true
```

```
❯ k get svc kubernetes-dashboard-kubernetes-dashboard-kong-proxy
NAME                                                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes-dashboard-kubernetes-dashboard-kong-proxy   ClusterIP   10.105.101.83   <none>        80/TCP,443/TCP   164m
```

Tunnel Binding configuration.

```
Annotations:  <none>
API Version:  networking.cfargotunnel.com/v1alpha1
Kind:         TunnelBinding
Metadata:
  Creation Timestamp:  2024-11-21T20:32:27Z
  Finalizers:
    cfargotunnel.com/finalizer
  Generation:        8
  Resource Version:  4997784
  UID:               af070c77-73d5-41c8-ba14-fa9163a1cfb9
Status:
  Hostnames:  dashboard.domain.com
  Services:
    Hostname:  dashboard.domain.com
    Target:    http://kubernetes-dashboard-kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc:80
Subjects:
  Kind:  Service
  Name:  kubernetes-dashboard-kubernetes-dashboard-kong-proxy
  Spec:
    Fqdn:           dashboard.domain.com
    No Tls Verify:  true
    Protocol:       http
    Proxy Address:  127.0.0.1
    Proxy Port:     0
    Proxy Type:
```

❯ k port-forward svc/kubernetes-dashboard-kubernetes-dashboard-kong-proxy 8080:80 -n kubernetes-dashboard

Work Just Fine without Cloudflare tunnel.

**Comment by adyanth** [comment]
If you are referring to this [k8s dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/), it serves its pages under https, and you are configuring the tunnel binding to connect as http. This wont work.

If the service only exposes port 443 (not 8443, and not 80 along with it) the default protocol selection logic would work fine. In this case, try the service target override instead:

```
subjects:
  - name: svcName
    spec:
      fqdn: svc.domain.com
      target: https://svcName.namespace.svc:8443
```

```bash
❯ k explain tunnelbinding.subjects.spec.protocol
GROUP:      networking.cfargotunnel.com
KIND:       TunnelBinding
VERSION:    v1alpha1

FIELD: protocol <string>


DESCRIPTION:
    Protocol specifies the protocol for the service. Should be one of http,
    https, tcp, udp, ssh or rdp.
    Defaults to http, with the exceptions of https for 443, smb for 139 and 445,
    rdp for 3389 and ssh for 22 if the service has a TCP port.
    The only available option for a UDP port is udp, which is default.
```

```bash
❯ k explain tunnelbinding.subjects.spec.target
GROUP:      networking.cfargotunnel.com
KIND:       TunnelBinding
VERSION:    v1alpha1

FIELD: target <string>


DESCRIPTION:
    Target specified where the tunnel should proxy to.
    Defaults to the form of
    <protocol>://<service.metadata.name>.<service.metadata.namespace>.svc:<port>
    
```

**Comment by Rahulsharma0810** [comment]
I Have tried both

```
subjects:
- name: kubernetes-dashboard-kubernetes-dashboard-kong-proxy
  spec:
    fqdn: kubedash.rvsharma.com
    target: http://kubernetes-dashboard-kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc:80
    protocol: http
    noTlsVerify: true
```

```
- name: kubernetes-dashboard-kubernetes-dashboard-kong-proxy
  spec:
    fqdn: kubedash.rvsharma.com
    target: https://kubernetes-dashboard-kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc:443
    protocol: https
    noTlsVerify: true
```

Both are giving same csrftoken error.
