### ISSUE TITLE
How to use tls certs

### ISSUE THREAD

**Issue by rollly00** [adyanth/cloudflare-operator#122]
Hi, strange question, but how can i use my own tls certs(tls.crt,tls.key) with CF Tunnel? Maybe I should specify it on my nginx container via mount secret. I didn't find anything about it, is it possible?

**Comment by mlanies** [comment]
Using your own TLS certificates with Cloudflare Tunnel (formerly Argo Tunnel) is indeed possible, but it requires a specific approach since Cloudflare Tunnel typically handles TLS termination for you.

Configure Your Nginx Container

```
server {
    listen 443 ssl;
    server_name yourdomain.com;

    ssl_certificate /etc/nginx/ssl/tls.crt;
    ssl_certificate_key /etc/nginx/ssl/tls.key;

    location / {
        proxy_pass http://localhost:8080;  # Adjust this to your backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```


Docker Compose
```
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./tls.crt:/etc/nginx/ssl/tls.crt
      - ./tls.key:/etc/nginx/ssl/tls.key
    ports:
      - "443:443"
```





config.yml

```
tunnel: your-tunnel-id
credentials-file: /path/to/credentials.json
ingress:
  - hostname: yourdomain.com
    service: https://your-nginx-container:443
    originRequest:
      noTLSVerify: true
```
