### ISSUE TITLE
Better instructions for the installation

### ISSUE THREAD

**Issue by gecube** [adyanth/cloudflare-operator#125]
Good day!

I want to ask for some guidance regarding installation of Cloudflare-operator with FluxCD toolkit. We are extensively using its' kustomization object, which can install a pack of manifests from arbitrary catalogue, but not the remote. Probably the documentation should be changed somewhere around: https://github.com/adyanth/cloudflare-operator/blob/main/docs/getting-started.md#deploy-the-operator or maybe just release some artifacts - like prebuilt yaml files for the basic installation of cf-operator or even suggest to deploy it with the Helm.

The benefits are obvious:
- clear and understandable way of the installation
- widening the user audience for the cf-operator

**Comment by adyanth** [comment]
Flux CD says it should support pulling from git repos? https://fluxcd.io/flux/faq/

**Comment by gecube** [comment]
@adyanth yep, but it would look like strange. Relatively strange. I'd prefer to do something like this:

https://github.com/artazar/flux2-general/blob/main/infra/crds/kustomization.yaml

**Comment by adyanth** [comment]
I am not sure if operator-sdk https://sdk.operatorframework.io/docs/building-operators/golang/migration/ provides such an output. I'm open to PRs!

**Comment by Rahulsharma0810** [comment]
I am using Flux in below ways

https://github.com/Rahulsharma0810/HomeLab-Kubernetes/tree/main/manifests/infrastructure/cloudflare-operator-system
https://github.com/Rahulsharma0810/HomeLab-Kubernetes/blob/main/manifests/cluster/flux-system/cloudflare-operator-system.yaml

**Comment by EpicStep** [comment]
@adyanth, I researched and I think that operator-sdk can create distributable YAML with all resources. Can you assign this issue to me?

**Comment by cyclingwithelephants** [comment]
For some more info, I'm using vanilla kustomize like 

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-operator-system

resources:
  - resources/cluster-tunnel.yaml
  - resources/dashboard.yaml
  - resources/external-secret-cloudflare.yaml
  - https://github.com/adyanth/cloudflare-operator.git/config/default?ref=v0.11.1

```
