### ISSUE TITLE
could not reuse already existing tunnel

### ISSUE THREAD

**Issue by gecube** [adyanth/cloudflare-operator#128]
Use case:

1. I have a ephemeral cluster. I set up tunnel. Everything works
2. I am destroying this cluster without resource cleanup (so definitely something will be left on CF side)
3. I want to create a new cluster with the same set of manifests.
4. Tunnel is not created.

It helps to change the manifest for the tunnel:

```yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: k3s-cluster-tunnel
spec:
  cloudflare:
    CLOUDFLARE_API_KEY: CLOUDFLARE_API_KEY
    CLOUDFLARE_API_TOKEN: CLOUDFLARE_API_TOKEN
    CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: CLOUDFLARE_TUNNEL_CREDENTIAL_FILE
    CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET
    accountId: ******
    domain: *******
    email: gb12335@gmail.com
    secret: cloudflare-secrets
  image: cloudflare/cloudflared:2024.9.1
  newTunnel:
    name: my-new-k8s-tunnel #### <-----
  noTlsVerify: false
  protocol: auto
```

Anyway the services are not available
