### ISSUE TITLE
Installation error: invalid request headers

### ISSUE THREAD

**Issue by thomaspetit** [adyanth/cloudflare-operator#131]
First of all, thanks for this awesome operator. Seems to fulfil all I need at first glance but sadly I can't even get it to boot/install:

```
2025-04-21T08:05:05Z	ERROR	error retrieving account details	{"controller": "clustertunnel", "controllerGroup": "networking.cfargotunnel.com", "controllerKind": "ClusterTunnel", "ClusterTunnel": {"name":"talos-cluster"}, "namespace": "", "name": "talos-cluster", "reconcileID": "77ee64b3-e9e3-49f1-badd-1aaab54f7c8e", "accountId": "<cloudflare_account_id", "error": "Invalid request headers (6003)"}
```

I've setup the following resources:

- kustomization
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/adyanth/cloudflare-operator/config/default?ref=v0.11.1
  - ./base

namespace: cloudflare-operator-system

patches:
  - target:
      kind: Namespace
      name: cloudflare-operator-system
    patch: |
      $patch: delete
      kind: Namespace
      metadata:
        name: cloudflare-operator-system
```

- secret
```
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-operator
  namespace: cloudflare-operator-system
type: Opaque
data:
  CLOUDFLARE_API_KEY: ++++++++
  CLOUDFLARE_API_TOKEN: ++++++++
```
- tunnel

```
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: talos-cluster
spec:
  newTunnel:
    name: talos-cluster
  size: 1
  cloudflare:
    domain: example.com
    secret: cloudflare-operator
    email: my@example.com
    accountId: cloudflare_account_id
```

Totally unclear to me what I need to provide to make it work. What is even more unclear is the fact that after the error a new one gets thrown that makes no sense as the account_id was provided.

```
2025-04-21T08:05:12Z	ERROR	found no account, check accountName	{"controller": "clustertunnel", "controllerGroup": "networking.cfargotunnel.com", "controllerKind": "ClusterTunnel", "ClusterTunnel": {"name":"talos-cluster"}, "namespace": "", "name": "talos-cluster", "reconcileID": "3d0d397d-6099-4e98-9b32-8fa6a3c7641f", "accountName": "", "error": "no account in response"}
```

Am I missing something totally obvious here?
