### ISSUE TITLE
Tunnel/ClusterTunnel resource should own the actual CF tunnel and not require manual intervention sometimes

### ISSUE THREAD

**Issue by cyclingwithelephants** [adyanth/cloudflare-operator#153]
I recently had a disaster recovery scenario in my lab, and found that the tunnel/clusterTunnel resource doesn't update the existing tunnel in CF. This currently requires manually deleting the tunnel so that the controller can progress.

I understand that there's a one time secret that is shared with the client and so tunnel re-creation is necessary, rather than updating the ref. 

Ownership could be determined with the TXT record associated with the DNS records.

Similarly, imo we should carry the same behaviour with DNS records for tunnelBinding resources

**Comment by adyanth** [comment]
> found that the tunnel/clusterTunnel resource doesn't update the existing tunnel in CF

Could you elaborate on this please? What was the step of events during DR, and at what state did this happen?

**Comment by cyclingwithelephants** [comment]
- the cluster's etcd state was wiped, and the tunnel in CF was not removed (expected)
- new cluster created
- cloudflare-operator and associated config deployed
- cloudflare-operator can't create a new tunnel because one already exists, and it won't delete the existing one

**Comment by adyanth** [comment]
Oh, having the etcd wiped and creating a new cluster means you would effectively need to follow the existing tunnel configuration, because from the perspective of the k8s cluster, it is an existing tunnel now. 

Maybe what this feature request could be for is to not have new/existing tunnel, but use a single tunnel that gets adopted if it exists or gets created otherwise. Does that make it better?

**Comment by adyanth** [comment]
I see what you mean. Yeah, makes sense to have a TXT record to prove ownership so it can be recreated.

There is a small problem in that though. The proving ownership part is problematic since this is an entirely new cluster. So unless there is an external operator level ID provided (something like what external-dns does), it would be difficult.

There is further complications of all the DNS records now not being owned by the operator either, since they prove ownership by using the tunnel ID which has now possibly been recreated, thus resulting in a new ID.

**Comment by adyanth** [comment]
> If we can't establish previous ownership, I do still think it would be a reasonable thing to do for cloudflare-operator to re-create the actual tunnel in cloudflare.

Recreating a k8s cluster looks a lot like having a new cluster elsewhere, while the old cluster is still running. If you accidentally create a tunnel with the same name in a new cluster, it would break **everything** in the old one. This was the reason why you have a new and existing cluster config right now, along with TXT records for tunnelbindings.

The above scenario is way too easy to occur accidentally (think applying the same manifests across clusters) that I would want it to succeed on one of them, even if that means in a DR scenario the setup cost is higher (as it should be since the finalizers weren't given a chance to run. I expect any custom resource that you delete without letting it be cleaned up would leave orphaned resources around).

I would also recommend etcd backups: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster

> Periodically backing up the etcd cluster data is important to recover Kubernetes clusters under disaster scenarios, such as losing all control plane nodes

**Comment by adyanth** [comment]
> I think we should clean up dns records on TunnelBinding clean up as well, btw.

We do do that! There is an issue with updating a tunnel binding where we wouldn't delete the old one, but deleting a tunnel binding should delete the DNS records attached.

**Comment by cyclingwithelephants** [comment]
> Recreating a k8s cluster looks a lot like having a new cluster elsewhere, while the old cluster is still running
> ...
> The above scenario is way too easy to occur accidentally (think applying the same manifests across clusters) 

Yeah I definitely appreciate that, what about having this behaviour behind a flag? Think it's too risky?

> I would also recommend etcd backups: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster

Ironically this happened when I was migrating a k3s cluster from sqlite to etcd, so that I could set up etcd backups 😅 

> We do do that! There is an issue with updating a tunnel binding where we wouldn't delete the old one, but deleting a tunnel binding should delete the DNS records attached.

Oh good point, I was forgetting when this problem occurred. If we already have an issue for the update behaviour, that's great

**Comment by adyanth** [comment]
Having code that accesses the CF api to delete/recreate an existing tunnel I would say is problematic regardless of it being behind a switch.

Also, I've been running this from 3 years and it has served me well 😀 
(I could do better on the node selection, I know)

```yaml

# After new install of k3s server, restore with
# cd /var/lib/rancher/k3s; mv server server.old; mkdir -p server/db; cd server
# tar -xzf k3s-server-backup-XXX.tgz
# zcat k3s-server-db-dump-XXX.gz | sqlite3 db/state.db
# OR
# cp k3s-server-db-backup-XXX.db db/state.db
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k3s-server-backup
  namespace: kube-system
spec:
  # 0100h every day
  schedule: "0 1 * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      # auto cleanup the job after 2.5 days or so
      ttlSecondsAfterFinished: 200000
      template:
        metadata:
          labels:
            app.kubernetes.io/name: k3s-server-backup
        spec:
          restartPolicy: OnFailure
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - k8s-master
          containers:
            - image: alpine:latest
              imagePullPolicy: IfNotPresent
              name: k3s-server-backup
              resources:
                limits:
                  memory: 100Mi
                  cpu: 100m
              volumeMounts:
                - mountPath: /server/
                  name: server
                  readOnly: true
                - mountPath: /backup/
                  name: backup
              command:
                - /bin/sh
                - -c
                - apk add sqlite &&
                  cd /server &&
                  echo Start server backup &&
                  tar czf /backup/k3s-server-backup-$(date +%F:%R).tgz --exclude *.sock --exclude db . &&
                  echo Done server backup &&
                  echo Start DB Dump &&
                  sqlite3 db/state.db .dump | gzip -c > /backup/k3s-server-db-dump-$(date +%F:%R).gz &&
                  echo Done DB Dump &&
                  echo Start DB Backup &&
                  sqlite3 db/state.db "VACUUM INTO '/backup/k3s-server-db-backup-$(date +%F:%R).db'" &&
                  echo Done DB Backup, cleaning up &&
                  find /backup -type f -mtime +60 -delete &&
                  echo Complete
          volumes:
            - name: server
              hostPath:
                path: /var/lib/rancher/k3s/server
                type: Directory
            - name: backup
              persistentVolumeClaim:
                claimName: k3s-server-backup
```
