### ISSUE TITLE
feature request: be able to specify a priorityClassName for the pods

### ISSUE THREAD

**Issue by bbigras** [adyanth/cloudflare-operator#163]

**Comment by adyanth** [comment]
Please use the deployPatch to modify the podSpec

https://github.com/adyanth/cloudflare-operator/blob/main/docs/migrations/crd/v1alpha2.md

**Comment by bbigras** [comment]
It works! Thank you very much!

If I have a tunnel that I want to run with a higher priority, should I also set `priorityClassName` on `cloudflare-operator-controller-manager`? with something like:

kustomization.yaml
```yaml
kind: Kustomization
namespace: cloudflare-operator-system
resources:
  - https://github.com/adyanth/cloudflare-operator.git//config/default?ref=v0.13.0

patches:
  - target:
      kind: Deployment
      name: cloudflare-operator-controller-manager
    path: priority-class-patch.yaml
```

priority-class-patch.yaml
```yaml
- op: replace
  path: /spec/template/spec/priorityClassName
  value: my-custom-class
```
