### ISSUE TITLE
Support for arm architecture container image

### ISSUE THREAD

**Issue by zulhfreelancer** [adyanth/cloudflare-operator#37]
I'm trying to run this operator in my Raspberry Pi cluster but it's failing. The pod is using `adyanth/cloudflare-operator:0.7.0` image.

Logs from crash-looping pod:

```
kube-rbac-proxy I0312 17:29:08.957510       1 main.go:190] Valid token audiences: 
kube-rbac-proxy I0312 17:29:08.957737       1 main.go:262] Generating self signed cert as no cert is provided
kube-rbac-proxy I0312 17:29:11.317761       1 main.go:311] Starting TCP socket on 0.0.0.0:8443
kube-rbac-proxy I0312 17:29:11.318714       1 main.go:318] Listening securely on 0.0.0.0:8443
manager standard_init_linux.go:228: exec user process caused: exec format error
```

When I checked the [images](https://hub.docker.com/r/adyanth/cloudflare-operator/tags), looks like there's only one arch is supported now; _amd64_. It would be great if there's container image for arm* for RPi users as well. _Should_ be [possible](https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04#step-4-building-executables-for-different-architectures), right?

\* I'm using _armv7l_ and _aarch64_ specifically

**Comment by zulhfreelancer** [comment]
GoReleaser can help speed-up the cross-compilation and release process - https://goreleaser.com/customization/build/

**Comment by adyanth** [comment]
Hey @zulhfreelancer thanks for trying this out! Yeah, I was pushing the job of setting up pipelines and building multi-arch till someone requested it :)

I will build and push with `docker buildx` for now if that works well since I am a bit new to the `operator-sdk` framework. Although I think I should just be able to plug and play goreleaser into this.

**Comment by zulhfreelancer** [comment]
That works for me. Thanks!

**Comment by adyanth** [comment]
Should be available for arm64 and armv7 now, let me know if that does not work.

**Comment by zulhfreelancer** [comment]
I can confirm the operator is running fine now using `adyanth/cloudflare-operator:0.7.0@sha256:2c1efbff57198fea7d9c53373c54df2fc49dce66654e43fb59e458bbd958b0dd` image. Thanks.

Now, I'm dealing with the crash-looping cloudflared pod itself. Since the `cloudflare/cloudflared:2022.3.1` [image](https://hub.docker.com/layers/cloudflare/cloudflared/2022.3.1/images/sha256-047e6a03394881d98bc0af1811c3be492b0ce2f1fd935753f0be0536ff788f80?context=explore) itself doesn't support arm, I guess the only option for me is to wait for them to release arm images to Dockerhub.

Related issues:
- https://github.com/cloudflare/cloudflared/issues/588
- https://github.com/cloudflare/cloudflared/issues/420
- https://github.com/cloudflare/cloudflared/issues/359
- https://github.com/cloudflare/cloudflared/issues/237

Is it possible for me to set which cloudflared image I want to use e.g. via environment variable or as a new field to ClusterTunnel manifest? Something like this (see the last line)?

```yaml
# clustertunnel.yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: k3s-cluster-tunnel      # The ClusterTunnel Custom Resource Name
spec:
  newTunnel:
    name: my-k8s-tunnel         # Name of your new tunnel on Cloudflare
  size: 2                       # This is the number of replicas for cloudflared
  cloudflare:
    email: email@domain.com     # Your email used to login to the Cloudflare Dashboard
    domain: example.com         # Domain under which the tunnel runs and adds DNS entries to
    secret: cloudflare-secrets  # The secret created before
    # accountId and accountName cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
    accountName: <Cloudflare account name>
    accountId: <Cloudflare account ID>
    cloudflaredImage: user/image:tag[@sha256:xxx] # Use this image for cloudflared pod (if set). Otherwise, fallback to `cloudflare/cloudflared` image.
```

**Comment by adyanth** [comment]
Oh man, I did not know they did not use a multi-arch image. Yes, you can set what image to run! Although I had easier updates in mind, it totally fits this usecase. Use the `clustertunnel.spec.image` to set it to any tag and you are golden.

https://github.com/adyanth/cloudflare-operator/blob/2f758d3b9799e4bd97ac717e2efa77c3cb1816ba/api/v1alpha1/tunnel_types.go#L101

```
# clustertunnel.yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: k3s-cluster-tunnel      # The ClusterTunnel Custom Resource Name
spec:
  newTunnel:
    name: my-k8s-tunnel         # Name of your new tunnel on Cloudflare
  size: 2                       # This is the number of replicas for cloudflared
############## Here!
  image: cloudflared:2022.3.1
  cloudflare:
    email: email@domain.com     # Your email used to login to the Cloudflare Dashboard
    domain: example.com         # Domain under which the tunnel runs and adds DNS entries to
    secret: cloudflare-secrets  # The secret created before
    # accountId and accountName cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
    accountName: <Cloudflare account name>
    accountId: <Cloudflare account ID>
```

And yeah, my docs haven't caught up to the features I've been adding, I promise to get around to doing that :)
