### ISSUE TITLE
Allow adding pod/node affinity

### ISSUE THREAD

**Issue by adyanth** [adyanth/cloudflare-operator#52]
It would be good to have pod/node affinity rules to schedule the replicas on nodes that might be a part of different availability zones or other such use cases.

**Comment by adyanth** [comment]
To expand this issue's scope, allow modifying any (?) pod spec content?

**Comment by adyanth** [comment]
Something like this could be useful to run the pods on nodes with a different ISP providing internet. This assumes that all nodes have a label called `isp` whose value is the name of the ISP.

```yaml
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: cfargotunnel.com/cluster-tunnel
                  operator: In
                  values:
                  - tunnel-name
              topologyKey: isp
            weight: 100
```
