### ISSUE TITLE
Allow custom proxyType setting

### ISSUE THREAD

**Issue by rgdev** [adyanth/cloudflare-operator#74]
Cloudflare has a [cool feature](https://developers.cloudflare.com/cloudflare-one/tutorials/kubectl/) allowing you to turn http traffic into tcp traffic which allow you to create a secure tunnel to access Kubernetes' API by exposing it as a socks proxy to kubectl.

 Would it be possible to expose the [origin.proxyType](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/ingress/#proxytype) parameter in the TunnelBinding specs ?

**Comment by adyanth** [comment]
This is new! Sure, I can add it.

**Comment by adyanth** [comment]
Would you mind trying the `adyanth/cloudflare-operator:pr-75` image for the operator pod's manager container?

Sample patch command:
```bash
kubectl -n cloudflare-operator-system patch deploy cloudflare-operator-controller-manager --patch '{"spec": {"template": {"spec": {"containers": [{"name": "manager","image": "adyanth/cloudflare-operator:pr-75"}]}}}}'
```

**Comment by rgdev** [comment]
I tried applying the new CRDs but i'm getting an error when Argo tries to apply the new yaml : 
`CustomResourceDefinition.apiextensions.k8s.io "tunnelbindings.networking.cfargotunnel.com" is invalid: spec.validation.openAPIV3Schema.properties[subjects].items.properties[spec].properties[proxyType].default: Unsupported value: "": supported values: ";socks"`

I'm not super familiar with the CRDs definition format but I think it might be caused by [the enum](https://github.com/adyanth/cloudflare-operator/blob/fr-74-proxy-type/config/crd/bases/networking.cfargotunnel.com_tunnelbindings.yaml#L119) not containing an empty value as proxyType allow both "" and "socks" in cloudflare doc ?

**Comment by adyanth** [comment]
The ; should have allowed empty values. Let me check that and get back.

**Comment by adyanth** [comment]
Does it work now?

**Comment by rgdev** [comment]
@adyanth I confirm ArgoCD was happy with the change in CRD.

I tested the feature with the following binding :  

```
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: k8s-apiserver-tunnel
  namespace: default
subjects:
  - name: kubernetes
    spec:
      fqdn: myk8stunnel.domain.tld
      target: tcp://kubernetes.default.svc:443
      protocol: tcp
      noTlsVerify: true # apiserver uses a selfsigned certificate
      proxyType: "socks"
tunnelRef:
  kind: ClusterTunnel
  name: mytunnel
```

Opened a tunnel on my workstation : 

    cloudflared access tcp --hostname myk8stunnel.domain.tld --url 127.0.0.1:45812


Patched my kubeconfig : 

```
apiVersion: v1
clusters:
- cluster:
    ...
    proxy-url: socks5://127.0.0.1:45812
```

And it works flawlessly with kubectl/lens so far 👍
