### ISSUE TITLE
Label: cfargotunnel.com/is-cluster-tunnel is always "false".

### ISSUE THREAD

**Issue by matthewhembree** [adyanth/cloudflare-operator#85]
[This](https://github.com/adyanth/cloudflare-operator/blob/c38e0cc14dceef41729f8f9852c5e3743d392bff/controllers/reconciler.go#L48) seems to be a singular static value.

```yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  annotations:
  finalizers:
  - cfargotunnel.com/finalizer
  generation: 2
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/part-of: cloudflare-operator
    cfargotunnel.com/app: cloudflared
    cfargotunnel.com/domain: ###
    cfargotunnel.com/id: ###
    cfargotunnel.com/is-cluster-tunnel: "false"
    cfargotunnel.com/name: ###
    cfargotunnel.com/tunnel: cluster-tunnel-tunnel0
  name: cluster-tunnel-tunnel0
```

It's not important to me, but just an observation.

Thanks!
