### ISSUE TITLE
Operator Deployment OOMKill.

### ISSUE THREAD

**Issue by matthewhembree** [adyanth/cloudflare-operator#86]
The memory limits might be a little too low. I wonder if anyone else is seeing the same with this version. I'm not doing anything fancy.

Version: `v0.10.0`

I needed to patch them to 400Mi (Not precise. I just picked a number):
```json
[
  {
    "op": "replace",
    "path": "/spec/template/spec/containers/1/resources/limits/memory",
    "value": "400Mi"
  }
]
```

Thanks!

<details open>
<summary>Edit: Removed an incorrect code line reference.</summary>
https://github.com/adyanth/cloudflare-operator/blob/c38e0cc14dceef41729f8f9852c5e3743d392bff/controllers/reconciler.go#L491
</details>

**Comment by adyanth** [comment]
I am assuming you mean the Cloudflare tunnel deployment and not the operator itself?

Mine seems to be running fine with the same limits, may I ask which version of cloudflared are you using?

**Comment by matthewhembree** [comment]
> I am assuming you mean the Cloudflare tunnel deployment and not the operator itself?

No, the operator.

This is the snippet from my kustomization.yaml:

```yaml
patches:
- path: patches/cloudflare-operator-controller-manager-resources.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: cloudflare-operator-controller-manager
```
